import test from 'node:test';
import assert from 'node:assert/strict';
import { executePaid, encode, NETWORK, USDC, type Purchase, type Dependencies, type Requirement, type Settlement } from './core.ts';
import { confirmUsdcSettlement } from './chain.ts';
const payer='0x'+'1'.repeat(40),treasury='0x'+'2'.repeat(40);
const requirement:Requirement={scheme:'exact',network:NETWORK,asset:USDC,amount:'250000',payTo:treasury,maxTimeoutSeconds:300,extra:{name:'USD Coin',version:'2'}};
const proof={x402Version:2,accepted:requirement,payload:{signature:'0x'+'3'.repeat(130),authorization:{from:payer,to:treasury,value:'250000',validAfter:'0',validBefore:'9999999999',nonce:'0x'+'4'.repeat(64)}}};
const settlement:Settlement={success:true,network:NETWORK,payer,transaction:'0x'+'5'.repeat(64)};
function setup(){const rows=new Map<string,Purchase>();let settlements=0,revenues=0;const deps:Dependencies={store:{async find(fingerprint){return rows.get(fingerprint)??null;},async claim(p){const existing=rows.get(p.fingerprint);if(existing)return{created:false,purchase:existing};rows.set(p.fingerprint,p);return{created:true,purchase:p};},async setSettlement(id,s){for(const p of rows.values())if(p.id===id)p.settlement=s;},async fail(id,state){for(const p of rows.values())if(p.id===id)p.state=state;},async finish(id,_e,eligible){for(const p of rows.values())if(p.id===id){p.state='SETTLED';if(eligible)revenues++;}}},verify:async()=>({isValid:true,payer}),settle:async()=>{settlements++;return settlement;},confirm:async()=>({confirmed:true}),fulfill:async()=>({actual:'output'}),internalPayers:new Set([treasury])};return{deps,rows,counts:()=>({settlements,revenues})};}
function input(payment:unknown=proof,body:unknown={q:1}){return{request:new Request('https://example.com/api/v1/intelligence/brief',{method:'POST',headers:payment?{'payment-signature':encode(payment)}:{}}),body,sku:'intel.brief',requirement,resource:'https://example.com/api/v1/intelligence/brief'};}
test('v2 challenge never verifies or settles',async()=>{const s=setup();const r=await executePaid(input(null),s.deps);assert.equal(r.status,402);assert.ok(r.headers.get('payment-required'));assert.deepEqual(s.counts(),{settlements:0,revenues:0});});
test('valid paid fulfillment and retry return same receipt without double settlement',async()=>{const s=setup();const first=await executePaid(input(),s.deps);const retry=await executePaid(input(),s.deps);assert.equal(first.status,200);assert.deepEqual(await first.json(),await retry.json());assert.deepEqual(s.counts(),{settlements:1,revenues:1});});
test('concurrent requests settle once',async()=>{const s=setup();const responses=await Promise.all(Array.from({length:12},()=>executePaid(input(),s.deps)));assert.equal(responses.filter(r=>r.status===200).length,1);assert.equal(s.counts().settlements,1);});
test('nonce replay with different body rejected',async()=>{const s=setup();await executePaid(input(),s.deps);assert.equal((await executePaid(input(proof,{q:2}),s.deps)).status,409);assert.equal(s.counts().settlements,1);});
test('modified signature with same authorization does not bypass replay guard',async()=>{const s=setup();await executePaid(input(),s.deps);const alternate={...proof,payload:{...proof.payload,signature:'0x'+'6'.repeat(130)}};assert.equal((await executePaid(input(alternate),s.deps)).status,409);assert.equal(s.counts().settlements,1);});
test('invalid verification never settles',async()=>{const s=setup();s.deps.verify=async()=>({isValid:false,payer});assert.equal((await executePaid(input(),s.deps)).status,402);assert.equal(s.counts().settlements,0);});
test('uncertain settlement is durable and never retried',async()=>{const s=setup();let attempts=0;s.deps.settle=async()=>{attempts++;throw new Error('timeout after submission');};assert.equal((await executePaid(input(),s.deps)).status,503);assert.equal((await executePaid(input(),s.deps)).status,409);assert.equal(attempts,1);assert.equal([...s.rows.values()][0].state,'RECONCILE');});
test('service failure happens before charging',async()=>{const s=setup();s.deps.fulfill=async()=>{throw new Error('down');};assert.equal((await executePaid(input(),s.deps)).status,503);assert.equal(s.counts().settlements,0);});
test('internal payer produces receipt but no realized revenue',async()=>{const s=setup();s.deps.internalPayers.add(payer);assert.equal((await executePaid(input(),s.deps)).status,200);assert.equal(s.counts().revenues,0);});
test('chain confirmation failure withholds fulfillment and revenue',async()=>{const s=setup();s.deps.confirm=async()=>{throw new Error('wrong chain');};assert.equal((await executePaid(input(),s.deps)).status,503);assert.equal(s.counts().revenues,0);assert.equal([...s.rows.values()][0].settlement?.transaction,settlement.transaction);});
test('wrong amount requirement rejected before settlement',async()=>{const s=setup();const altered={...proof,accepted:{...requirement,amount:'1'}};assert.equal((await executePaid(input(altered),s.deps)).status,400);assert.equal(s.counts().settlements,0);});
test('independent receipt requires matching USDC transfer, canonical safe block',async()=>{const s=setup();await executePaid(input(),s.deps);const p=[...s.rows.values()][0];const transfer={address:USDC,topics:['0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef','0x'+'0'.repeat(24)+payer.slice(2),'0x'+'0'.repeat(24)+treasury.slice(2)],data:'0x3d090'};const rpc=async(method:string,params:unknown[])=>method==='eth_chainId'?'0x2105':method==='eth_getTransactionReceipt'?{status:'0x1',transactionHash:settlement.transaction,blockNumber:'0x20',blockHash:'hash',logs:[transfer]}:params[0]==='safe'?{number:'0x21'}:{hash:'hash'};assert.equal((await confirmUsdcSettlement(rpc,settlement,p)).grossAtomic,'250000');transfer.data='0x1';await assert.rejects(()=>confirmUsdcSettlement(rpc,settlement,p),/transfer mismatch/);});
