/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as CapitalRouteImport } from './routes/capital'
import { Route as CommerceRouteImport } from './routes/commerce'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as FactoryRouteImport } from './routes/factory'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as LiquidityRouteImport } from './routes/liquidity'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as YieldRouteImport } from './routes/yield'
import { Route as AtlasIdRouteImport } from './routes/atlas.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalRoute = CapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => rootRouteImport,
} as any)
const CommerceRoute = CommerceRouteImport.update({
  id: '/commerce',
  path: '/commerce',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const FactoryRoute = FactoryRouteImport.update({
  id: '/factory',
  path: '/factory',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const LiquidityRoute = LiquidityRouteImport.update({
  id: '/liquidity',
  path: '/liquidity',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const YieldRoute = YieldRouteImport.update({
  id: '/yield',
  path: '/yield',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasIdRoute = AtlasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AtlasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRouteWithChildren
  '/capital': typeof CapitalRoute
  '/commerce': typeof CommerceRoute
  '/developers': typeof DevelopersRoute
  '/factory': typeof FactoryRoute
  '/intelligence': typeof IntelligenceRoute
  '/launch': typeof LaunchRoute
  '/liquidity': typeof LiquidityRoute
  '/markets': typeof MarketsRoute
  '/network': typeof NetworkRoute
  '/yield': typeof YieldRoute
  '/atlas/$id': typeof AtlasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRouteWithChildren
  '/capital': typeof CapitalRoute
  '/commerce': typeof CommerceRoute
  '/developers': typeof DevelopersRoute
  '/factory': typeof FactoryRoute
  '/intelligence': typeof IntelligenceRoute
  '/launch': typeof LaunchRoute
  '/liquidity': typeof LiquidityRoute
  '/markets': typeof MarketsRoute
  '/network': typeof NetworkRoute
  '/yield': typeof YieldRoute
  '/atlas/$id': typeof AtlasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRouteWithChildren
  '/capital': typeof CapitalRoute
  '/commerce': typeof CommerceRoute
  '/developers': typeof DevelopersRoute
  '/factory': typeof FactoryRoute
  '/intelligence': typeof IntelligenceRoute
  '/launch': typeof LaunchRoute
  '/liquidity': typeof LiquidityRoute
  '/markets': typeof MarketsRoute
  '/network': typeof NetworkRoute
  '/yield': typeof YieldRoute
  '/atlas/$id': typeof AtlasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/capital'
    | '/commerce'
    | '/developers'
    | '/factory'
    | '/intelligence'
    | '/launch'
    | '/liquidity'
    | '/markets'
    | '/network'
    | '/yield'
    | '/atlas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/capital'
    | '/commerce'
    | '/developers'
    | '/factory'
    | '/intelligence'
    | '/launch'
    | '/liquidity'
    | '/markets'
    | '/network'
    | '/yield'
    | '/atlas/$id'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/capital'
    | '/commerce'
    | '/developers'
    | '/factory'
    | '/intelligence'
    | '/launch'
    | '/liquidity'
    | '/markets'
    | '/network'
    | '/yield'
    | '/atlas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRouteWithChildren
  CapitalRoute: typeof CapitalRoute
  CommerceRoute: typeof CommerceRoute
  DevelopersRoute: typeof DevelopersRoute
  FactoryRoute: typeof FactoryRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LaunchRoute: typeof LaunchRoute
  LiquidityRoute: typeof LiquidityRoute
  MarketsRoute: typeof MarketsRoute
  NetworkRoute: typeof NetworkRoute
  YieldRoute: typeof YieldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capital': {
      id: '/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof CapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commerce': {
      id: '/commerce'
      path: '/commerce'
      fullPath: '/commerce'
      preLoaderRoute: typeof CommerceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/factory': {
      id: '/factory'
      path: '/factory'
      fullPath: '/factory'
      preLoaderRoute: typeof FactoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liquidity': {
      id: '/liquidity'
      path: '/liquidity'
      fullPath: '/liquidity'
      preLoaderRoute: typeof LiquidityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yield': {
      id: '/yield'
      path: '/yield'
      fullPath: '/yield'
      preLoaderRoute: typeof YieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/$id': {
      id: '/atlas/$id'
      path: '/$id'
      fullPath: '/atlas/$id'
      preLoaderRoute: typeof AtlasIdRouteImport
      parentRoute: typeof AtlasRoute
    }
  }
}

interface AtlasRouteChildren {
  AtlasIdRoute: typeof AtlasIdRoute
}

const AtlasRouteChildren: AtlasRouteChildren = {
  AtlasIdRoute: AtlasIdRoute,
}

const AtlasRouteWithChildren = AtlasRoute._addFileChildren(AtlasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRouteWithChildren,
  CapitalRoute: CapitalRoute,
  CommerceRoute: CommerceRoute,
  DevelopersRoute: DevelopersRoute,
  FactoryRoute: FactoryRoute,
  IntelligenceRoute: IntelligenceRoute,
  LaunchRoute: LaunchRoute,
  LiquidityRoute: LiquidityRoute,
  MarketsRoute: MarketsRoute,
  NetworkRoute: NetworkRoute,
  YieldRoute: YieldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
